$path = 'frontend/src/main.jsx'
$content = [System.IO.File]::ReadAllText((Join-Path (Get-Location) $path), [System.Text.Encoding]::UTF8)
$replacements = @(
    @('import React,{useEffect,useState} from ''react'';', 'import React,{useEffect,useRef,useState} from ''react'';'),
    @('SlidersHorizontal,Waypoints,Zap', 'SlidersHorizontal,Volume2,VolumeX,Waypoints,Zap'),
    @('[answer,setAnswer]=useState(null),[loading,setLoading]=useState(false);', '[answer,setAnswer]=useState(null),[loading,setLoading]=useState(false),[voiceEnabled,setVoiceEnabled]=useState(true),[voiceText,setVoiceText]=useState('''');const updateTimer=useRef(null),requestSeq=useRef(0);'),
    @('async function refresh(c=css,s=srp){try{const r=await fetch(`${API}/wells/BGW-001/state`);let w=await r.json();w.css=c;w.srp=s;const saved=await fetch(`${API}/wells/BGW-001/state`,{method:''PUT'',headers:{''Content-Type'':''application/json''},body:JSON.stringify(w)});setData(await saved.json())}catch(e){console.error(e)}}', 'function speak(text){setVoiceText(text);if(!voiceEnabled)return;if(!(''speechSynthesis'' in window)){setVoiceText(''Speech output is not supported in this browser.'');return}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=''en-IN'';utterance.rate=1;window.speechSynthesis.speak(utterance)}async function refresh(c=css,s=srp,announce=false){const requestId=++requestSeq.current;try{const r=await fetch(`${API}/wells/BGW-001/state`);let w=await r.json();if(requestId!==requestSeq.current)return;w.css=c;w.srp=s;const saved=await fetch(`${API}/wells/BGW-001/state`,{method:''PUT'',headers:{''Content-Type'':''application/json''},body:JSON.stringify(w)});const next=await saved.json();if(requestId!==requestSeq.current)return;setData(next);if(announce){const level=next.risk_score>.65?''dangerous'':next.risk_score>.3?''caution'':''normal'';speak(`Update complete. Risk status ${level}. Modeled oil rate ${next.oil_rate_m3d} cubic meters per day. Reservoir temperature ${next.reservoir_temp_c} degrees Celsius.`)}}catch(e){console.error(e)}}'),
    @('return()=>clearInterval(t)', 'return()=>{clearInterval(t);clearTimeout(updateTimer.current);window.speechSynthesis?.cancel()}'),
    @('const setC=(k,v)=>{const n={...css,[k]:Number(v)};setCss(n);refresh(n,srp)},setS=(k,v)=>{const n={...srp,[k]:Number(v)};setSrp(n);refresh(css,n)};', 'const queueUpdate=(c,s)=>{clearTimeout(updateTimer.current);updateTimer.current=setTimeout(()=>refresh(c,s,true),300)};const setC=(k,v)=>{const n={...css,[k]:Number(v)};setCss(n);queueUpdate(n,srp)},setS=(k,v)=>{const n={...srp,[k]:Number(v)};setSrp(n);queueUpdate(css,n)};'),
    @('<button className="outline" onClick={save}>Save scenario</button>', '<button className="outline voice-toggle" onClick={()=>setVoiceEnabled(!voiceEnabled)}>{voiceEnabled?<Volume2 size={13}/>:<VolumeX size={13}/>} Voice {voiceEnabled?''on'':''off''}</button><button className="outline" onClick={save}>Save scenario</button>'),
    @('{answer&&<div className="answer"><b>{answer.summary}</b><ul>{answer.drivers.map(d=><li key={d}>{d}</li>)}</ul><small>{answer.caveat}</small></div>}', '{answer&&<div className="answer"><b>{answer.summary}</b><ul>{answer.drivers.map(d=><li key={d}>{d}</li>)}</ul><div className="answer-actions"><button className="outline listen-button" onClick={()=>speak(`${answer.summary} ${answer.drivers.join(''. '')}`)}><Volume2 size={14}/> Listen to explanation</button><span aria-live="polite">{voiceText}</span></div><small>{answer.caveat}</small></div>}')
)
foreach ($pair in $replacements) {
    if (-not $content.Contains($pair[0])) { throw "Target text not found: $($pair[0].Substring(0, [Math]::Min(90, $pair[0].Length)))" }
    $content = $content.Replace($pair[0], $pair[1])
}
[System.IO.File]::WriteAllText((Join-Path (Get-Location) $path), $content, [System.Text.UTF8Encoding]::new($false))
